### ISSUE TITLE
The Great Version 1.0 Checklist

### ISSUE THREAD

**Issue by bachmacintosh** [bachmacintosh/wanikani-api-types#6]
# Current ETA for Version 1.0

**December 11th, 2022**

# Meta

## GitHub Repo

- [x] Create Issue and Pull Request templates to better organize them, make sure we have all the info we need, things look neat, etc.
- [x] No blocking Issues/PRs after other items completed

## TypeScript

- [x] Support TypeScript 4.9 when it becomes stable

## Renovate

- [x] Make sure TypeScript devDependency and peerDependency are updated completely independent from everything else on major and minor versions; TS isn't SemVer, and should be called out separately from other deps just used for development

# Modules / Exports

- [x] Make sure all items can be imported across various TypeScript project types that use Node.js and ES Modules
- [x] Evaluate Deno support and complexity of generating and hosting Deno `.ts` files -- **Tested against Deno via `esm.sh`, able to import types, methods, and constants.**
- [x] Remove all deprecated items once ready to bump to 1.0.0

# Functions

- [x] Write Unit Tests for all functions

# Types

## Base

- [x] Export some constants of non-union type aliases, e.g. max levels
- [x] Write type guards for WaniKani Levels -- individual numbers and arrays of level numbers

## Collections/Data/Reports/Resources

Make sure all types match what is returned by the API:

- [x] Assignments
- [x] Level Progressions
- [x] Resets
- [x] Reviews
- [x] Review Statistics
- [x] Spaced Repetition Systems
- [x] Study Materials
- [x] Subjects
- [x] Summary
- [x] User
- [x] Voice Actors

## Parameters

Make sure parameters work as expected after stringification, i.e. use the query parameters in Postman:

- [x] Assignments
- [x] Level Progressions
- [x] Resets
- [x] Reviews
- [x] Review Statistics
- [x] Spaced Repetition Systems
- [x] Study Materials
- [x] Subjects
- [x] Voice Actors

## Payloads

Try sending payloads after running through `JSON.stringify()`, and make sure WaniKani accepts the data:

- [x] Start Assignment
- [x] Create Review
- [x] Create/Update Study Materials
- [x] Update User Preferences

Verify the response structure that we get back from submitting the payload is correctly typed:

- [x] Started Assignment
- [x] Created Review
- [x] Created/Updated Study Materials
- [x] Updated User

### Related Issues

- [x] #13 

# Docs

- [x] Proof-read documentation, make sure wording is consistent, spelling/grammar/punctuation are OK, etc.
- [x] Clarify difference between importing from main module vs revision modules, e.g. `import {} from "@bachmacintosh/wanikani-api-types";` vs `import {} from "@bachmacintosh/wanikani-api-types/v20170710.js";`
- [x] Make more/better usage example(s) in README
